kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: control-plane
- role: control-plane
- role: worker
  extraPortMappings:
  - containerPort: 30000        
    hostPort: 8761              
    listenAddress: "0.0.0.0"    
    protocol: tcp
- role: worker
  extraPortMappings:
  - containerPort: 30001        
    hostPort: 8082              
    listenAddress: "0.0.0.0"    
    protocol: tcp
- role: worker
  extraPortMappings:
  - containerPort: 30002        
    hostPort: 8080              
    listenAddress: "0.0.0.0"    
    protocol: tcp
- role: worker
  extraPortMappings:
  - containerPort: 30003        
    hostPort: 8081              
    listenAddress: "0.0.0.0"    
    protocol: tcp
- role: worker
  extraPortMappings:
  - containerPort: 30004        
    hostPort: 8083              
    listenAddress: "0.0.0.0"    
    protocol: tcp
